export const mockClientData = {
  overview: {
    activeMissions: 3,
    completedMissions: 12,
    pendingInvoices: 2,
    totalSpent: 45600,
  },
  missions: [
    {
      id: "M001",
      title: "Website Redesign Project",
      consultant: "Sarah Johnson",
      status: "In Progress",
      startDate: "2024-01-15",
      endDate: "2024-03-15",
      budget: 15000,
      progress: 65,
    },
    {
      id: "M002",
      title: "Mobile App Development",
      consultant: "Mike Chen",
      status: "Planning",
      startDate: "2024-02-01",
      endDate: "2024-05-01",
      budget: 25000,
      progress: 15,
    },
    {
      id: "M003",
      title: "SEO Optimization",
      consultant: "Emma Davis",
      status: "In Progress",
      startDate: "2024-01-20",
      endDate: "2024-02-20",
      budget: 5600,
      progress: 80,
    },
    {
      id: "M004",
      title: "Brand Identity Design",
      consultant: "Alex Rodriguez",
      status: "Completed",
      startDate: "2023-11-01",
      endDate: "2023-12-15",
      budget: 8500,
      progress: 100,
    },
  ],
  invoices: [
    {
      id: "INV-001",
      missionTitle: "Website Redesign Project",
      amount: 7500,
      status: "Paid",
      dueDate: "2024-01-30",
      issueDate: "2024-01-15",
    },
    {
      id: "INV-002",
      missionTitle: "SEO Optimization",
      amount: 2800,
      status: "Pending",
      dueDate: "2024-02-15",
      issueDate: "2024-02-01",
    },
    {
      id: "INV-003",
      missionTitle: "Mobile App Development",
      amount: 12500,
      status: "Overdue",
      dueDate: "2024-01-25",
      issueDate: "2024-01-10",
    },
  ],
  payments: [
    {
      id: "PAY-001",
      invoiceId: "INV-001",
      amount: 7500,
      method: "Credit Card",
      date: "2024-01-28",
      status: "Completed",
    },
    {
      id: "PAY-002",
      invoiceId: "INV-004",
      amount: 8500,
      method: "Bank Transfer",
      date: "2024-12-20",
      status: "Completed",
    },
    {
      id: "PAY-003",
      invoiceId: "INV-002",
      amount: 2800,
      method: "Credit Card",
      date: "2024-02-10",
      status: "Processing",
    },
  ],
  notifications: [
    {
      id: "N001",
      title: "Nouvelle Facture Disponible",
      message: "Facture INV-002 pour le projet SEO Optimization est maintenant disponible.",
      type: "invoice",
      date: "2024-02-01",
      read: false,
    },
    {
      id: "N002",
      title: "Mission Progress Update",
      message: "Website Redesign Project is now 65% complete.",
      type: "mission",
      date: "2024-01-30",
      read: true,
    },
    {
      id: "N003",
      title: "Payment Confirmation",
      message: "Your payment of $7,500 has been processed successfully.",
      type: "payment",
      date: "2024-01-28",
      read: true,
    },
  ],
}

export const mockConsultantData = {
  overview: {
    activeMissions: 5,
    totalHours: 156,
    thisWeekHours: 32,
    upcomingDeadlines: 3,
  },
  missions: [
    {
      id: "M001",
      title: "Website Redesign Project",
      client: "TechCorp Inc.",
      status: "In Progress",
      deadline: "2024-03-15",
      hoursLogged: 45,
      totalHours: 80,
      priority: "High",
      description: "Complete redesign of corporate website with modern UI/UX",
    },
    {
      id: "M005",
      title: "E-commerce Platform",
      client: "RetailMax",
      status: "Planning",
      deadline: "2024-04-01",
      hoursLogged: 12,
      totalHours: 120,
      priority: "Medium",
      description: "Build custom e-commerce solution with payment integration",
    },
    {
      id: "M006",
      title: "Mobile App Development",
      client: "StartupXYZ",
      status: "In Progress",
      deadline: "2024-05-15",
      hoursLogged: 28,
      totalHours: 200,
      priority: "High",
      description: "Native iOS and Android app development",
    },
  ],
  timeEntries: [
    {
      id: "T001",
      missionId: "M001",
      missionTitle: "Website Redesign Project",
      date: "2024-02-01",
      hours: 8,
      description: "Frontend development and responsive design implementation",
    },
    {
      id: "T002",
      missionId: "M001",
      missionTitle: "Website Redesign Project",
      date: "2024-01-31",
      hours: 6,
      description: "Client meeting and requirements gathering",
    },
    {
      id: "T003",
      missionId: "M005",
      missionTitle: "E-commerce Platform",
      date: "2024-02-02",
      hours: 4,
      description: "Database schema design and planning",
    },
  ],
  absences: [
    {
      id: "A001",
      type: "Vacation",
      startDate: "2024-03-01",
      endDate: "2024-03-05",
      status: "Approved",
      reason: "Family vacation",
    },
    {
      id: "A002",
      type: "Sick Leave",
      startDate: "2024-02-15",
      endDate: "2024-02-15",
      status: "Approved",
      reason: "Medical appointment",
    },
  ],
  notifications: [
    {
      id: "N001",
      title: "New Mission Assigned",
      message: "You have been assigned to Mobile App Development project.",
      type: "mission",
      priority: "high",
      date: "2024-02-01",
      read: false,
    },
    {
      id: "N002",
      title: "Time Entry Reminder",
      message: "Don't forget to log your hours for today.",
      type: "reminder",
      priority: "medium",
      date: "2024-02-01",
      read: true,
    },
  ],
}

export const mockAdminData = {
  overview: {
    totalClients: 24,
    totalConsultants: 12,
    activeMissions: 18,
    monthlyRevenue: 125000,
    pendingInvoices: 8,
    overduePayments: 3,
  },
  clients: [
    {
      id: "C001",
      name: "TechCorp Inc.",
      email: "contact@techcorp.com",
      phone: "+1 (555) 123-4567",
      activeMissions: 2,
      totalSpent: 45600,
      joinDate: "2023-06-15",
      status: "Active",
      industry: "Technology",
    },
    {
      id: "C002",
      name: "RetailMax",
      email: "info@retailmax.com",
      phone: "+1 (555) 987-6543",
      activeMissions: 1,
      totalSpent: 28900,
      joinDate: "2023-08-22",
      status: "Active",
      industry: "Retail",
    },
    {
      id: "C003",
      name: "StartupXYZ",
      email: "hello@startupxyz.com",
      phone: "+1 (555) 456-7890",
      activeMissions: 3,
      totalSpent: 67200,
      joinDate: "2023-09-10",
      status: "Active",
      industry: "Fintech",
    },
  ],
  consultants: [
    {
      id: "CON001",
      name: "Sarah Johnson",
      email: "sarah@oncreesaas.com",
      specialization: "Frontend Development",
      activeMissions: 3,
      totalHours: 245,
      joinDate: "2023-03-10",
      status: "Active",
      hourlyRate: 85,
    },
    {
      id: "CON002",
      name: "Mike Chen",
      email: "mike@oncreesaas.com",
      specialization: "Mobile Development",
      activeMissions: 2,
      totalHours: 189,
      joinDate: "2023-05-18",
      status: "Active",
      hourlyRate: 90,
    },
    {
      id: "CON003",
      name: "Emma Davis",
      email: "emma@oncreesaas.com",
      specialization: "UI/UX Design",
      activeMissions: 1,
      totalHours: 156,
      joinDate: "2023-07-22",
      status: "Active",
      hourlyRate: 75,
    },
  ],
  allMissions: [
    {
      id: "M001",
      title: "Website Redesign Project",
      client: "TechCorp Inc.",
      consultant: "Sarah Johnson",
      status: "In Progress",
      startDate: "2024-01-15",
      endDate: "2024-03-15",
      budget: 15000,
      progress: 65,
    },
    {
      id: "M002",
      title: "Mobile App Development",
      client: "StartupXYZ",
      consultant: "Mike Chen",
      status: "Planning",
      startDate: "2024-02-01",
      endDate: "2024-05-01",
      budget: 25000,
      progress: 15,
    },
    {
      id: "M003",
      title: "SEO Optimization",
      client: "RetailMax",
      consultant: "Emma Davis",
      status: "In Progress",
      startDate: "2024-01-20",
      endDate: "2024-02-20",
      budget: 5600,
      progress: 80,
    },
  ],
  allInvoices: [
    {
      id: "INV-001",
      client: "TechCorp Inc.",
      missionTitle: "Website Redesign Project",
      amount: 7500,
      status: "Paid",
      dueDate: "2024-01-30",
      issueDate: "2024-01-15",
    },
    {
      id: "INV-002",
      client: "RetailMax",
      missionTitle: "SEO Optimization",
      amount: 2800,
      status: "Pending",
      dueDate: "2024-02-15",
      issueDate: "2024-02-01",
    },
    {
      id: "INV-003",
      client: "StartupXYZ",
      missionTitle: "Mobile App Development",
      amount: 12500,
      status: "Overdue",
      dueDate: "2024-01-25",
      issueDate: "2024-01-10",
    },
  ],
  allPayments: [
    {
      id: "PAY-001",
      client: "TechCorp Inc.",
      invoiceId: "INV-001",
      amount: 7500,
      method: "Credit Card",
      date: "2024-01-28",
      status: "Completed",
    },
    {
      id: "PAY-002",
      client: "RetailMax",
      invoiceId: "INV-004",
      amount: 8500,
      method: "Bank Transfer",
      date: "2024-12-20",
      status: "Completed",
    },
  ],
  notifications: [
    {
      id: "N001",
      title: "System Maintenance",
      message: "Scheduled maintenance on Sunday 3 AM - 5 AM EST.",
      type: "system",
      priority: "medium",
      date: "2024-02-01",
      read: false,
    },
    {
      id: "N002",
      title: "New Client Registration",
      message: "StartupXYZ has completed registration and verification.",
      type: "client",
      priority: "low",
      date: "2024-01-30",
      read: true,
    },
  ],
}
